---
- name: install virtualenv
  apt:
    pkg: virtualenv
    state: present

- name: install the python-dev linux headers
  apt:
    pkg: python-dev
    state: present

- name: pip install requirements.txt
  pip:
    requirements: "{{ h_virtualenv_requirements_path }}"
    extra_args: --use-wheel
    virtualenv: "{{ h_virtualenv_base }}"
    virtualenv_python: "{{ h_virtualenv_python }}"

- name: pip install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ h_virtualenv_base }}"
    virtualenv_python: "{{ h_virtualenv_python }}"
